# Generated by Django 4.1.2 on 2022-10-21 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(upload_to='images/company_logos')),
                ('team_and_background', models.TextField()),
                ('company_and_products', models.TextField()),
                ('problem_to_solve', models.TextField()),
                ('solution', models.TextField()),
                ('value_proposition_for_customer', models.TextField()),
                ('competetors', models.TextField()),
                ('revenue_model', models.TextField()),
                ('market_size', models.TextField()),
                ('market_plan', models.TextField()),
                ('type_of_incubation', models.CharField(choices=[('Physical Incubation', 'Physical Incubation'), ('Virtual Incubation', 'Virtual Incubation')], max_length=100)),
                ('business_proposal', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
