# Generated by Django 4.1.2 on 2022-10-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incubation',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company_logos'),
        ),
    ]
