# Generated by Django 4.1.2 on 2022-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_incubation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='is_slot_allotted',
            field=models.BooleanField(default=False),
        ),
    ]
