# Generated by Django 4.1.2 on 2022-10-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_incubation_is_slot_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
