# Generated by Django 4.1.2 on 2022-10-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incubation'),
        ),
    ]
